-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2020-05-25 22:58:55 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


CREATE TABLE country4 (
    country_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE country4 ADD CONSTRAINT country4_pk PRIMARY KEY ( country_name );

CREATE TABLE location4 (
    city_name               VARCHAR2(20),
    country_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE location4 ADD CONSTRAINT location4_pk PRIMARY KEY ( city_name,
                                                                country_name );


CREATE TABLE place4 (
    latitude                          NUMBER(9, 6) NOT NULL,
    longitude                         NUMBER(9, 6) NOT NULL,
    city_name                         VARCHAR2(20) NOT NULL,  
    country_name                      VARCHAR2(20) NOT NULL
);

ALTER TABLE place4 ADD CONSTRAINT place4_pk PRIMARY KEY ( longitude,
                                                          latitude );
                                                          
CREATE TABLE event4 (
    event_id           INTEGER NOT NULL,
    longitude          NUMBER(9, 6) NOT NULL,
    latitude           NUMBER(9, 6) NOT NULL
);

ALTER TABLE event4 ADD CONSTRAINT event4_pk PRIMARY KEY ( event_id );     

CREATE TABLE user4 (
    username   VARCHAR2(30) NOT NULL
);

ALTER TABLE user4 ADD CONSTRAINT user4_pk PRIMARY KEY ( username );


CREATE TABLE user_event4 (
    event_id   INTEGER NOT NULL,
    username    VARCHAR2(30) NOT NULL
);

ALTER TABLE user_event4 ADD CONSTRAINT user_event4_pk PRIMARY KEY ( event_id,
                                                                    username );



CREATE TABLE comment4 (
    comment_id                    INTEGER NOT NULL,
    comment_text                  VARCHAR2(1000),
    event_id                      INTEGER NOT NULL,
    username                      VARCHAR2(30) NOT NULL
);

ALTER TABLE comment4 ADD CONSTRAINT comment4_pk PRIMARY KEY ( comment_id );



CREATE TABLE extra4 (
    shape                 VARCHAR2(20),
    duration_sec          INTEGER,
    datetime              TIMESTAMP,
    comment_id            INTEGER NOT NULL
);

ALTER TABLE extra4 ADD CONSTRAINT extra4_pk PRIMARY KEY ( comment_id );



ALTER TABLE location4
    ADD CONSTRAINT location4_country4_fk FOREIGN KEY ( country_name )
        REFERENCES country4 ( country_name );

ALTER TABLE place4
    ADD CONSTRAINT place4_location4_fk FOREIGN KEY ( city_name,
                                                     country_name )
        REFERENCES location4 ( city_name,
                               country_name );
                               
ALTER TABLE event4
    ADD CONSTRAINT event4_place4_fk FOREIGN KEY ( longitude,
                                                  latitude )
        REFERENCES place4 ( longitude,
                            latitude );                              

ALTER TABLE user_event4
    ADD CONSTRAINT user_event4_event4_fk FOREIGN KEY ( event_id )
        REFERENCES event4 ( event_id );

ALTER TABLE user_event4
    ADD CONSTRAINT user_event4_user4_fk FOREIGN KEY ( username )
        REFERENCES user4 ( username );

ALTER TABLE comment4
    ADD CONSTRAINT comment4_user_event4_fk FOREIGN KEY ( event_id,
                                                         username )
        REFERENCES user_event4 ( event_id,
                                 username );


ALTER TABLE extra4
    ADD CONSTRAINT extra4_comment4_fk FOREIGN KEY ( comment_id )
        REFERENCES comment4 ( comment_id );





